### ISSUE TITLE
500 error when requesting for date 2010-07-25

### ISSUE THREAD

**Issue by nathanhosselton** [nasa/apod-api#1]
Requests made to the API with the data parameter set for July 25, 2010 fail with an internal server error.

Request:
`https://api.nasa.gov/planetary/apod?date=2010-07-25&api_key=DEMO_KEY`

Response:
```
{
  "code": 500, 
  "msg": "Internal Service Error", 
  "service_version": "v1"
}
```

The date's APOD is valid and available though as it can be viewed at https://apod.nasa.gov/apod/ap100725.html

Presumably the underlying issue could affect other dates but this is the only one that I have surfaced so far and I'm unable to identify a potential cause to test further. For example, though the media type for this date is a video, other dates for which the content is a video do not share the problem.

**Comment by AdrianBinDC** [comment]
I plugged in that date with a valid API key and it returns a response. Try changing `api_key=DEMO_KEY` to a valid API key.

**Comment by JustinGOSSES** [comment]
was not an actual issue but demo key exceeded call limits
