### ISSUE TITLE
API returns error code 503 (Service Unavailable) but APOD site running fine.

### ISSUE THREAD

**Issue by FrosterDune** [nasa/apod-api#108]
When I try to connect to API and get the JSON dictionary data, it throws error 503 (Service Unavailable) It's been 17 hours since the issue started. There is a stack trace of the error:

> Error occurred at 05.06.2023 14:11:46:
Response status code does not indicate success: 503 (Service Unavailable).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at AstronomyPictureOfTheDayWallpaperApp.WallpaperAPODloader.LoadPicture() in C:\Users\FrosterDune\source\repos\AstronomyPictureOfTheDayWallpaperApp\AstronomyPictureOfTheDayWallpaperApp\WallpaperAPODloader.cs:line 56
   at AstronomyPictureOfTheDayWallpaperApp.MainForm.ActivateBT_Click(Object sender, EventArgs e) in C:\Users\FrosterDune\source\repos\AstronomyPictureOfTheDayWallpaperApp\AstronomyPictureOfTheDayWallpaperApp\MainForm.cs:line 68

**Comment by jc8654** [comment]
I've reported this to the NASA CIO Operations - they're looking into it.

**Comment by faizov** [comment]
Very long :(

**Comment by Rafayqayyum** [comment]
> When I try to connect to API and get the JSON dictionary data, it throws error 503 (Service Unavailable) It's been 17 hours since the issue started. There is a stack trace of the error:
> 
> > Error occurred at 05.06.2023 14:11:46:
> > Response status code does not indicate success: 503 (Service Unavailable).
> > at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
> > at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
> > at AstronomyPictureOfTheDayWallpaperApp.WallpaperAPODloader.LoadPicture() in C:\Users\FrosterDune\source\repos\AstronomyPictureOfTheDayWallpaperApp\AstronomyPictureOfTheDayWallpaperApp\WallpaperAPODloader.cs:line 56
> > at AstronomyPictureOfTheDayWallpaperApp.MainForm.ActivateBT_Click(Object sender, EventArgs e) in C:\Users\FrosterDune\source\repos\AstronomyPictureOfTheDayWallpaperApp\AstronomyPictureOfTheDayWallpaperApp\MainForm.cs:line 68

The apod api is down for now, I hope they fix it soon.

**Comment by koust6u** [comment]
Hurry up and fix it, you aliens. I'm using this API for my assignment. Please fix it

**Comment by oliveratgithub** [comment]
You guys are funny for not having a fallback for when a third-party API is not working 👀

No issues on our website when the APOD API doesn't return a daily pic… 😎
https://github.com/zorgch/zorg-code/blob/f10957c28c7f3402936b50f85e1614d40444191a/www/includes/apod.inc.php#L73

**Comment by faizov** [comment]
> 



> Вы, ребята, забавны тем, что у вас нет запасного варианта, когда сторонний API не работает.👀
> 
> На нашем веб-сайте нет проблем, когда API APOD не возвращает ежедневное изображение…😎 https://github.com/zorgch/zorg-code/blob/f10957c28c7f3402936b50f85e1614d40444191a/www/includes/apod.inc.php#L73

parsing apod.nasa.gov?

**Comment by faizov** [comment]
> You guys are funny for not having a fallback for when a third-party API is not working 👀
> 
> No issues on our website when the APOD API doesn't return a daily pic… 😎 https://github.com/zorgch/zorg-code/blob/f10957c28c7f3402936b50f85e1614d40444191a/www/includes/apod.inc.php#L73

It doesn't work on your site :)

**Comment by InformatikEule** [comment]
same problem here. sadface.jpg hope they fix it soon.

**Comment by StellarStoic** [comment]
`Service temporarily unavailable. Please try again later. (Status Code: 503)
` I'll just post manually to my [bot](https://snort.social/p/npub1ap0dw55xedm5w4mkcyq8m7xyluwfc680lywrvfe50vr9ckl5m3uqtf5l75) for now :)

**Comment by StellarStoic** [comment]
`Service temporarily unavailable. Please try again later. (Status Code: 503)`

I'll just post manually for the time being :)

**Comment by vegerot** [comment]
I'm getting a 503 when trying to access the NASA APOD API.  I've never used any of the other NASA APIs.  Can anyone confirm if those are working?

**Comment by faizov** [comment]
> I'm getting a 503 when trying to access the NASA APOD API. I've never used any of the other NASA APIs. Can anyone confirm if those are working?


Others work

**Comment by peimansh** [comment]
Now it's returning:
502 Bad Gateway

**Comment by Murzify** [comment]
Please fix it. My app doesn’t work

**Comment by koust6u** [comment]
please please please please please

**Comment by cody0303** [comment]
It's now a 502 Bad Gateway. Progress? Negative progress? Unclear.

**Comment by eglezalo** [comment]
Some time this morning it said i've used my key a bit too much. Right now the 502 bad gateway error is back

**Comment by Murzify** [comment]
"no healthy upstream", wow, that’s progress

**Comment by martinsuchan** [comment]
Same problem here, getting more and more reports from users of my app that they are not getting new pictures.

**Comment by Hideman85** [comment]
The issue persists... 503 here

**Comment by Dan-Banfield** [comment]
> When I try to connect to API and get the JSON dictionary data, it throws error 503 (Service Unavailable) It's been 17 hours since the issue started. There is a stack trace of the error:
> 
> > Error occurred at 05.06.2023 14:11:46:
> > Response status code does not indicate success: 503 (Service Unavailable).
> > at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
> > at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
> > at AstronomyPictureOfTheDayWallpaperApp.WallpaperAPODloader.LoadPicture() in C:\Users\FrosterDune\source\repos\AstronomyPictureOfTheDayWallpaperApp\AstronomyPictureOfTheDayWallpaperApp\WallpaperAPODloader.cs:line 56
> > at AstronomyPictureOfTheDayWallpaperApp.MainForm.ActivateBT_Click(Object sender, EventArgs e) in C:\Users\FrosterDune\source\repos\AstronomyPictureOfTheDayWallpaperApp\AstronomyPictureOfTheDayWallpaperApp\MainForm.cs:line 68

Yup. It's down for everyone. The API returns "no healthy upstream." I have a .NET MAUI mobile app written in C# called APOD which uses this data, and it fails to load it now.

**Comment by CArrandale** [comment]
Cool. It's working. Now let's not give it the hug of death you guys. Plz I like my pretty space images.

**Comment by StellarStoic** [comment]
Confirmed. Bots working again 👏

**Comment by FrosterDune** [comment]
Ok, The problem is still not solved yet, again I got 504 gateway timeout error code and now it will hold the 60s before throwing this error code

**Comment by Dan-Banfield** [comment]
> Was working for a few hours. Getting a 504 Gateway Time-out now. 
> 
> My Error Page is finally getting some love :')

Same here 😞

**Comment by eglezalo** [comment]
> Was working for a few hours. Getting a 504 Gateway Time-out now.
> 
> My Error Page is finally getting some love :')

Same same :(

**Comment by abpei** [comment]
I just return a picture of a black hole when the API does not hand me anything useful.

**Comment by lohith-hg** [comment]
504 Gateway Time-out

**Comment by ItsDimitrie** [comment]
It worked for like a day again, they when looking again today I just doesn't load anymore and returns a 504 error. Hopefully it can be fixed soon as I used the API for a school assignment!

**Comment by Nerdomante** [comment]
Same problem here, I developed an app that changes my wallpaper with the daily APOD, but it hasn't been able to reach the endpoint for a few days now. It keeps returning a 503 error. It worked for a brief moment and then stopped again. Such a shame because I don't want to miss out on any of them :(

**Comment by Ovid** [comment]
`504 Gateway Time-out`

I sat down yesterday to write a new web service using this API and it worked a couple of times (yesterday), and then stopped. I was wondering if I had done something wrong and was getting throttled. Happy to know it's not me. Unhappy to know this has been going on so long.

**Comment by faizov** [comment]
> `504 Gateway Time-out`
> 
> I sat down yesterday to write a new web service using this API and it worked a couple of times (yesterday), and then stopped. I was wondering if I had done something wrong and was getting throttled. Happy to know it's not me. Unhappy to know this has been going on so long.

The problem is on the api side

**Comment by faizov** [comment]
504 Gateway Time-out

**Comment by RemzieK** [comment]
It's working now!

**Comment by FrosterDune** [comment]
It works again, I will reopen this issue if the problem reappears, but I hope it won't be needed

**Comment by TheKicker** [comment]
Working great on my website, thanks for fixing it gang! 🚀

**Comment by Ovid** [comment]
Also, if anyone's interested, I'm starting an unofficial [NASA OpenAPI specification](https://github.com/Ovid/nasa-openapi). It's part of another project I'm working on that will hopefully capture all endpoints available at [api.nasa.gov](https://api.nasa.gov). I only have three endpoints so far, but that's because I'm upgrading my local software to handle some unexpected edge cases.
