### ISSUE TITLE
The API is down

### ISSUE THREAD

**Issue by thisiskeanyvy** [nasa/apod-api#109]
- The API seems to have stopped working on 9 June 2023

![down](https://github.com/nasa/apod-api/assets/48371699/3740e323-42b4-487c-85b9-65fde66d9609)

https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY

**Comment by memmer57** [comment]
Same here

**Comment by thisiskeanyvy** [comment]
Resolved
