### ISSUE TITLE
Very long time to get data

### ISSUE THREAD

**Issue by faizov** [nasa/apod-api#112]
It takes a very long time to get data from https://api.nasa.gov/planetary/apod

Request is in pending status and drops from 504, sometimes works immediately

**Comment by jc8654** [comment]
I'm seeing a similar issue however it's sporadic and inconsistent. Sometimes a request comes back immediately - other times it takes so long the call I have to the API (via PHP get) times out.

Around 6-7pm ET 28 June 2023, it was intermittent with some requests working, and some not. I've been looking at for the last 15-20 minutes or so, and now it's timing out with a 504 error (around 9:45pm ET 28 June).

**Comment by faizov** [comment]
> I'm seeing a similar issue however it's sporadic and inconsistent. Sometimes a request comes back immediately - other times it takes so long the call I have to the API (via PHP get) times out.
> 
> Around 6-7pm ET 28 June 2023, it was intermittent with some requests working, and some not. I've been looking at for the last 15-20 minutes or so, and now it's timing out with a 504 error (around 9:45pm ET 28 June).

This is almost always the case with me. I keep track of it on my [website ](https://nasa-pet.vercel.app/) and in my [Telegram bot](https://t.me/nasabotphoto_bot). The repositories are different, but the response from apod is equally long.
