### ISSUE TITLE
API responds with 504 error code

### ISSUE THREAD

**Issue by najwer23** [nasa/apod-api#122]
![Zrzut ekranu 2024-05-17 070152](https://github.com/nasa/apod-api/assets/52133025/09b8b118-531e-4089-bff3-7a8773795009)

**Comment by solumath** [comment]
Have the same problem with 
`https://api.nasa.gov/planetary/apod?api_key={nasa_key}&concept_tags=True`
and with
`https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY `
the page with daily picture works, does it use different API?
https://apod.nasa.gov/apod/astropix.html

**Comment by imprvhub** [comment]
Exactly the same problem here. Error 504. What else can we do besides communicate? Sorry guys, there's a 504 from NASA, you won't be able to use the app until NASA fixes it.
<img width="1065" alt="Captura de pantalla 2024-05-17 a la(s) 09 02 32" src="https://github.com/nasa/apod-api/assets/133716241/17df9962-8a39-473c-a764-fd0062a0774e">

**Comment by najwer23** [comment]
Oh I was thinking that we have some1 from NASA here. In my opinion it is the good move that they don't use the same API as everyone.

**Comment by najwer23** [comment]
it s working!
