### ISSUE TITLE
APOD is not working

### ISSUE THREAD

**Issue by Sandeep1829** [nasa/apod-api#14]
While calling the api it is giving a sever application error message.Even the DEMO_KEY is not working.
Please respond soon.

**Comment by hemangshah** [comment]
Can you share the API URL which is not working for you? @Sandeep1829

**Comment by Sandeep1829** [comment]
https://api.nasa.gov/planetary/apod?api_key=ypTe8kEN1mY1NkvFT9MQhy0kW9BAXrv6j9bKOjZF

**Comment by hemangshah** [comment]
Hi @Sandeep1829 , please delete your last message as it contains actual key. 🔥

**Comment by Sandeep1829** [comment]
@hemangshah please check this url too.

https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY

**Comment by hemangshah** [comment]
🔥🔥🔥 This is scary 👻it's not working for me too. @Sandeep1829 .

**Comment by Sandeep1829** [comment]
What to do now.I need to complete my project soon

**Comment by PawelPleskaczynski** [comment]
Yep, it's not working for me as well. You can use my own API though, it's really easy to deploy on Heroku, take a look here: https://github.com/PawelPleskaczynski/apod_api

**Comment by PawelPleskaczynski** [comment]
Anyways, NASA seems to be doing nothing with this API, eg. I made a pull request that fixes some issues with 500 error and they just ignored it :pensive:

**Comment by jgdv** [comment]
I'm getting what appears to be correct info from the DEMO_KEY url now - seemed like a temporary outage maybe?

**Comment by hemangshah** [comment]
@Sandeep1829 , You're absolutely right that without this you can't complete your project but believe me the same API is using by my live app and users already complained it about this issue. God knows when this API dev team will look into this issue. Mean while as **Pawel** commented his API is great and you should use if you are in very hurry to complete your project. His API also provided various other features which is not available in NASA's API and will save a good amount of development time of yours.

**Comment by Sandeep1829** [comment]
Thanks Paweł Pleskaczyński. Can I use this for my android app

**Comment by PawelPleskaczynski** [comment]
Wow, weird, it's working for me as well. It wasn't working literally a couple minutes ago

**Comment by hemangshah** [comment]
Oh yes, it's working for me too now. 🤨🎉

**Comment by Sandeep1829** [comment]
Really.

**Comment by hemangshah** [comment]
May be people out there getting our conversation notifications 🤔

**Comment by Sandeep1829** [comment]
Oh yeah.It's working for me too now.

**Comment by hemangshah** [comment]
@PawelPleskaczynski , guessing they have uploaded it on heroku server and may be the issues from there?

**Comment by JustinGOSSES** [comment]
Looking into this, but probably need to talk to people not working due to government shut-down. There was another spat of 503 messages associated with a small slice of the APOD traffic on January 7th as well. Post here if you experience more problems. Thank you.

**Comment by elveatles** [comment]
I'm getting a 500 error with this URL https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY&start_date=2018-10-01&end_date=2018-10-31.

The response body is:

`{
    "code": 500,
    "msg": "Internal Service Error",
    "service_version": "v1"
}`

What's weird is it works for the following month. URL: https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY&start_date=2018-11-01&end_date=2018-11-30

**Comment by PawelPleskaczynski** [comment]
@elveatles that's because there's one single day (2018-10-07) that's breaking the API because the APOD in this day is neither an image, nor a video. My pull request, which fixes these errors, was merged, but it seems it wasn't pushed to the api.nasa.gov website.

**Comment by elveatles** [comment]
@PawelPleskaczynski Good to know. Hopefully it will be pushed soon.

**Comment by pabloegpf1** [comment]
The Heroku server is intermittently responding with 500 internal server error. I cannot believe NASA made this API public and did not fix this problem, a lot of projects are basically useless if this API fails.

**Comment by brianthomas** [comment]
This API is hosted as an example to test integrate with, not for production support.  Please download the code and host locally for your own production service.

=brian

**Comment by PawelPleskaczynski** [comment]
> This API is hosted as an example to test integrate with, not for production support. Please download the code and host locally for your own production service. 

@brianthomas 
Why does NASA treat the [public API](https://api.nasa.gov/planetary/apod) as an example? I didn't know about that, and I'm sure not many people think it's not a production-ready API. If it's _just an example_, why an API key is needed?

**Comment by opZywl** [comment]
stop again:
