### ISSUE TITLE
2019-01-23 returns an incorrect encoding for "š" in copyright

### ISSUE THREAD

**Issue by JakeSteam** [nasa/apod-api#17]
The [APOD for this day](https://api.nasa.gov/planetary/apod?date=2019-01-23&api_key=DEMO_KEY) returns `Luk\u00e1\u009a Vesel\u00fd` as the `copyright` field.

This `\u009a` character does not represent `š`. According to [the Unicode Latin-1 supplement](https://www.unicode.org/charts/PDF/U0080.pdf), `\u009a` is *Single Character Introducer*, which can't be displayed graphically. `š` should instead be ` \u0161`.

The copyright should therefore be `Luk\u00e1\u0161 Vesel\u00fd`

This was initially raised on [the JSON parsing library GSON](https://github.com/google/gson/issues/1459), where there's a little more info.

**Comment by kpanicc** [comment]
Code point \u009a represents _LATIN SMALL LETTER S WITH CARON_ in the [CP1252](https://unicode.org/Public/MAPPINGS/VENDORS/MICSFT/WINDOWS/CP1252.TXT) encoding.

But, as specified in [RFC 7159](https://tools.ietf.org/html/rfc7159#page-9) JSON must be encoded with UTF-8/16/32.

The API might be using the wrong encoding when treating special characters.

**Comment by JakeSteam** [comment]
Ah, thank you for finding CP1252 @kpanicc , that explains why [sites like this](http://www.fileformat.info/info/unicode/char/9a/index.htm) showed `š` in `.toString()`s etc.

Definitely an encoding issue, using CP1252 when it shouldn't be.
