### ISSUE TITLE
Obtaining an API key with higher limits.

### ISSUE THREAD

**Issue by Fieel** [nasa/apod-api#20]
Hello,

i used the APOD API in my first app which i built to learn using the Ionic Framework. The app is free/ad-free and i published it in the play store some days ago.

Some months ago i contacted NASA through various e-mail addresses i found in the API and contact pages (such as this one https://data.nasa.gov/Space-Science/Astronomy-Picture-of-the-Day-API/ez2w-t8ua) but still no response. I fear my limit will be exceeded quickly as soon as some people download and start using the app.

As stated in the website:

> For each API key, these limits are applied across all api.nasa.gov API requests. Exceeding these limits will lead to your API key being temporarily blocked from making further requests. The block will automatically be lifted by waiting an hour. **If you need higher rate limits, contact us.**

But i can't manage to contact them :(

What can i do? Thanks.

**Comment by JustinGOSSES** [comment]
There are many apps that get a fair amount of traffic without problems. You should be fine. If different IPs are using your key, you shouldn't have a problem. If you're using the APOD API only, you can even download that code (also on github) and run it yourself on heroku, which would result in you setting your own rate limits.

I'll make a note to clear this up in documentation.

**Comment by Fieel** [comment]
Thanks @JustinGOSSES , you're correct to this day I didn't hit the limit yet even though [my app](https://play.google.com/store/apps/details?id=com.fieel.nasaAPOD) is currently installed in hundreds of devices. Thanks for your reply.
