### ISSUE TITLE
Title formatted incorrectly

### ISSUE THREAD

**Issue by pabloegpf1** [nasa/apod-api#23]
There is a number of JSON responses that have "Information:" in the title field. This is an example:
https://api.nasa.gov/planetary/apod?api_key=uBHdRJkKAl917xAmxxaAqtRig5PtTzotpfw5v9v4&date=1996-09-21

**Comment by hemangshah** [comment]
Assuming eventually they have improved the API so now actual title is coming.

**Comment by JustinGOSSES** [comment]
this seems fixed

**Comment by pabloegpf1** [comment]
This is not fixed, you can check the title field of the example from my first comment.

`title: "Information:"`

**Comment by JustinGOSSES** [comment]
Misunderstood the issue, so reopening. 

I've created a possible fix in this pull request https://github.com/JustinGOSSES/apod-api/pull/1

It needs more extensive testing than I have time for right now. 

**If anyone else would like to help**, please clone the fork, stand up a local version and test across a range of dates to make sure it always gives the right title. You might run the current API in the master branch and this one on a large number of dates, than evaluate the differences in predicted titles by hand.

Thank you.

**Comment by JustinGOSSES** [comment]
https://github.com/nasa/apod-api/pull/34
