### ISSUE TITLE
Thumbs Parameter | 400 Error

### ISSUE THREAD

**Issue by itsHall** [nasa/apod-api#32]
Today's request returns a 400 error when using the `thumbs` parameter:

https://api.nasa.gov/planetary/apod?api_key={api_key}&date=2020-01-21&hd=true&thumbs=true

Full Message:

`{"code":400,"msg":"Bad Request: incorrect field passed. Allowed request fields for apod method are 'concept_tags', 'date', 'hd', 'count', 'start_date', 'end_date'","service_version":"v1"}`

The documentation says the parameter is ignored if not a video. This is a video, but I'm guessing the way the url was entered as an embed (https://www.youtube.com/embed/hgzGET6owYk?rel=0) caused the thumbnail creation to break?

**Comment by qalandarov** [comment]
@itsHall, you're exposing your API key and the thumbnail is coming fine now

**Comment by itsHall** [comment]
@qalandarov Whoops, thanks!

**Comment by qalandarov** [comment]
@itsHall, you only edited the text, but the link still has your key 🙂

**Comment by itsHall** [comment]
@qalandarov you're a hero! haha, thank you 👍🏻
