### ISSUE TITLE
2020/06/04 is showing yesterday´s picture

### ISSUE THREAD

**Issue by IsaTTeN** [nasa/apod-api#37]
Hello, in the APOD for 2020/06/04 is showing the yesterday´s picture:

`{"date":"2020-06-03",
"explanation":"very time Venus passes the Earth, it shows the same face.  This remarkable fact has been known for only about 50 years, ever since radio telescopes have been able to peer beneath Venus' thick clouds and track its slowly rotating surface.  This inferior conjunction -- when Venus and Earth are the closest -- occurs today.  The featured animation shows the positions of the Sun, Venus and Earth between 2010-2023 based on NASA-downloaded data, while a mock yellow 'arm' has been fixed to the ground on Venus to indicate rotation.  The reason for this unusual 1.6-year resonance is the gravitational influence that Earth has on Venus, which surprisingly dominates the Sun's tidal effect.  If Venus could be seen through the Sun's glare today, it would show just a very slight sliver of a crescent. Although previously visible in the evening sky, starting tomorrow, Venus will appear in the morning sky -- on the other side of the Sun as viewed from Earth.   Experts Debate: How will humanity first discover extraterrestrial life?",
"media_type":"video",
"service_version":"v1",
"title":"The Dance of Venus and Earth",
"url":"https://www.youtube.com/embed/Cd5a5KdPxQc?rel=0"}`

**Comment by jeffstjean** [comment]
I sent an email to their contact page. Will update if there's any response but noticed the same issue.

**Comment by samyanez94** [comment]
In my case, requesting `https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY&date=2020-06-04` is returning `"Internal Service Error"`. Is anyone else having this issue?

**Comment by jeffstjean** [comment]
Yes, just tried it and same deal.

**Comment by evantayloryates** [comment]
This should be resolved now

**Comment by samyanez94** [comment]
Looking good from my end. Thanks @evantayloryates

**Comment by IsaTTeN** [comment]
@evantayloryates thanks, but I realised this morning is happening the same again. Today is showing the yesterday´s picture unfortunately
