### ISSUE TITLE
When 20-06-10 (a day in which there is no apod) is used or included in a date interval request, makes the whole request go 500 internal service error.

### ISSUE THREAD

**Issue by Peloponeso31** [nasa/apod-api#38]
My app which does use this feature of your API just does not work as consequence :(

end_date=2020-06-9:
![image](https://user-images.githubusercontent.com/32084752/84469394-94103600-ac46-11ea-9a35-f0d83adc2fe6.png)

end_date=2020-06-10
![image](https://user-images.githubusercontent.com/32084752/84469379-8a86ce00-ac46-11ea-9273-c7b7f31ae386.png)

**Comment by hemangshah** [comment]
There is an error returning for the specific date i.e. 10th June 2020

https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY&start_date=2020-06-08&end_date=2020-06-09

I think it won't uploaded yet on their server.

**Comment by Peloponeso31** [comment]
> There is an error returning for the specific date i.e. 10th June 2020
> 
> https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY&start_date=2020-06-08&end_date=2020-06-09 (This is working fine)
> 
> https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY&start_date=2020-06-08&end_date=2020-06-10 (Error)
> 
> I think it won't uploaded yet on their server.

I have just realized that day no apod was posted.
Shouldn't the API just not include the no upload days instead of making the whole request invalid?

**Comment by hemangshah** [comment]
Yes, you're right, but for some reason its not up-to-date. You can use this API - https://github.com/PawelPleskaczynski/apod_api

**Comment by JustinGOSSES** [comment]
This is fixed by a change in behavior when no image exists on APOD. Now, a default image is used if an image doesn't exist for that day on APOD.

 However, other people disagreed with this fix https://github.com/nasa/apod-api/issues/40

Please let us know if you would prefer this situation to result in an error or the default image when one doesn't exist.

**Comment by MarcusOtter** [comment]
I believe this issue has been resolved and can be closed, see discussion in #40.
