### ISSUE TITLE
API can't load big lists of APODs

### ISSUE THREAD

**Issue by PawelPleskaczynski** [nasa/apod-api#4]
I can't use API's `start_date`: when I set the minimal date to a few years ago, I'm getting this message: 

> An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

I can't even set the `start_date` to 2017-01-01 😞

**Comment by eringrand** [comment]
I _think_ the problem is that there are a few days that don't seem to work (#1 ), and if you try and pull a range with those dates init you get an error back.

**Comment by hemangshah** [comment]
@eringrand , You're right. I just came across this issue.

https://github.com/nasa/apod-api/issues/8
