### ISSUE TITLE
Fallback image for missing/corrupted asset

### ISSUE THREAD

**Issue by martinsuchan** [nasa/apod-api#40]
Hi, my app received in the last couple of days placeholder image instead of the real image trhought the API with the text:

> This is a fallback image used in the case where there is a missing/corrupted asset on apod.nasa.gov. Image source: https://en.wikipedia.org/wiki/File:Black_Hole_in_the_universe.jpg

Wondering is this just a temporary glitch, is it possible to detect these temporary placeholders somehow in my app, or not return these placeholders by the API at all? Thanks.

![apodhd-2020-06-26-default_apod_image](https://user-images.githubusercontent.com/3041397/85826516-0162b180-b785-11ea-9fd8-00a7d7dc13a7.jpg)

**Comment by hemangshah** [comment]
This is interesting !!

**Comment by JustinGOSSES** [comment]
This is an attempt to fill the gap when the APOD page changes their syntax or doesn't have an image that the API can programmatically grab. The APOD API is working fine here, just the page the photo is being scraped form isn't formatted properly for it to work.

What alternative behavior would you want? 

Tagging @evantayloryates

**Comment by martinsuchan** [comment]
@JustinGOSSES the alternative behavior is simple, either return valid json and image, or just return NotFound 404 status code until the image and json for the given day is available.
Returning placeholder image is really not a good practice, especially when the placeholder response is completely valid. Many apps or websites is caching those responses and they won't ask for another image for given day after receiving the placeholder response.

**Comment by JustinGOSSES** [comment]
It seems different people want different things then. 

Others have expressed an interest in getting some image back when the APOD site (totally separate from this API and run by totally different people) changes the structure of their HTML enough that an image can't be found by the APOD API. 

Unfortunately, the admin's of this API don't have the time to support immediate development of code changes to fix edge cases. Changes often occurs weeks or months later. Public contributions are of course always welcome!

If you want to be able to detect when the API fails to find an image on APOD, you can check the image and text. The image above and associated text will remain the same any time the APOD API can't find them on the APOD site. You could modify your code to look for this response and change behavior accordingly. Would this work for you?

**Comment by martinsuchan** [comment]
@JustinGOSSES Just a note, returning valid response, that is in fact a placeholder, goes against RESTful API design best practices. If some websites want to show placeholder, they should do it on their side.
Right now I've added checks to my proxy server and to my apps to look for the placeholder string and if it's found in the response, the response is considered invalid. It works, but it's not a nice solution.

**Comment by LeMorrow** [comment]
Personally I think that when you ask for a date interval and one of the dates within that interval happen to be invalid/missing/whatever, it shouldn't throw a 404 for the entire request. But it also shouldn't return a placeholder. It should just not return that entry. It's up to the application developers to check if a specific date they asked for within that interval exists or not. It should not, like @martinsuchan mentions, be up to the developers to check if the string is a placeholder or not.

When you ask for a specific date (like 20-06-10), it should return a 404. And when you ask for a random APOD and it happens to land on a missing image, it should re-pick and return only existing images instead.

Thoughts?

**Comment by martinsuchan** [comment]
@LeMorrow yeah, exactly

- asking for specified date which has no APOD data available? -> 404
- asking for interval of APOD images, some of them not available? -> return json array only with data for available dates
- asking for random APOD day? -> return one of existing APOD dates. This request should never fail.

**Comment by JustinGOSSES** [comment]
Thanks for laying it out clearly like that @martinsuchan 

@evantayloryates do you have an opinion on this?

**Comment by evantayloryates** [comment]
I think the requested behavior here is good and pretty simple to implement. I will work on a patch for this over the next few days, as time allows, and update the thread when I've pushed to production.

**Comment by evantayloryates** [comment]
@martinsuchan @LeMorrow @hemangshah @JustinGOSSES I pushed the fix to production. Here are a couple of URLs you can check to test the behavior (2020-06-10 is a known missing APOD date):

http://apodapi-env-test.us-east-1.elasticbeanstalk.com/v1/apod/?date=2020-06-10
https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY&start_date=2020-06-08&end_date=2020-06-12

**Comment by evantayloryates** [comment]
@martinsuchan @LeMorrow @hemangshah @JustinGOSSES I pushed the fix to production. Here are a couple of URLs you can check to test the behavior (2020-06-10 is a known missing APOD date):

https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY&date=2020-06-10
https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY&start_date=2020-06-08&end_date=2020-06-12

**Comment by evantayloryates** [comment]
I'm going to close this issue. If there are any other behavior changes you'd like implemented, feel free to open up a new issue
