### ISSUE TITLE
Unit test and CI question

### ISSUE THREAD

**Issue by vn7n24fzkq** [nasa/apod-api#44]
Is there are any plan for CI like github action and unit test for flask api ?

**Comment by JustinGOSSES** [comment]
Would love to get this repo set up with some basic runs of the test coverage via github actions. We're always going to be a little slow getting to pull requests here, but would gladly accept a pull request of this type.

**Comment by JustinGOSSES** [comment]
Follow-up comment about this.... the test need work. They don't work correctly anymore. Would be a great pull request possiblity.
