### ISSUE TITLE
Several questions / suggestions.

### ISSUE THREAD

**Issue by nwunderly** [nasa/apod-api#49]
So I'm developing an async python wrapper for the NASA APIs as a side project. As I worked on the APOD part I noticed some things. I also, since finding this repository, have thought of some questions about design decisions made with regard to this API.

1. The `date` parameter defaults to "today", which I figured out means "today UTC" because starting at exactly midnight UTC the API throws a 404 until that day's page is uploaded. Was this intentional? It seems like it would make more sense to, when no date parameters are passed, default to the most recent valid date.

2. I noticed this API is literally just pulling the data from the APOD website directly. Is there a reason you're not using a cache system or a database of any kind? It seems like this wouldn't be difficult to implement but would make maintaining the API significantly easier.

**Comment by nwunderly** [comment]
Also worth noting that the API documentation doesn't mention the `start_date`/`end_date` or `count` parameters. Not sure how difficult it is to update that webpage but that would be useful to have in the documentation.

**Comment by JustinGOSSES** [comment]
This is just a scrapper API. The people who run APOD and that respond to this repo are entirely different. 

The comment about "start_date" has been fixed now.
