### ISSUE TITLE
What is the X-RateLimit-Limit span of time?

### ISSUE THREAD

**Issue by AdrianBinDC** [nasa/apod-api#5]
What is the span of time on which the `X-RateLimit-Limit` server response is determined? I think it's per hour, but I'm not 100% sure.

**Comment by hemangshah** [comment]
Yes, it's per hour. I have read it on their website.

**Comment by JakeSteam** [comment]
Yep, it's hourly:

> The hourly counters for your API key reset on a rolling basis.

https://api.nasa.gov/api.html#how-do-i-see-my-current-usage?
