### ISSUE TITLE
API key trouble. Please help.

### ISSUE THREAD

**Issue by alexjederock** [nasa/apod-api#56]
My api key is getting a 403 error, which is strange because it worked fine last night when I went to bed. Is the API down or something?

**Comment by elementh** [comment]
Seems to be working fine for me, could you share your calls? Maybe there is something wrong with them!

**Comment by alexjederock** [comment]
Hey I appreciate the response, I ended up figuring it out. My .env saved the closing paranthesis an entire line down which was strange. Thanks anyway!

**Comment by elementh** [comment]
@alexjederock I'm glad you solved it! Please don't forget to close the issue :)
