### ISSUE TITLE
Wrong image link on 2018-08-06

### ISSUE THREAD

**Issue by PawelPleskaczynski** [nasa/apod-api#6]
Hello, there's a wrong image link when I'm requesting 2018-08-06 APOD: https://apod.nasa.gov/apod/http://nusoft.fnal.gov/nova/public/img/FD-evt-echo.gif

Should be http://nusoft.fnal.gov/nova/public/img/FD-evt-echo.gif

**Comment by hemangshah** [comment]
+1 

I am about to open the same issue @PawelPleskaczynski – Thanks for reporting.

**Comment by JustinGOSSES** [comment]
Looks as if two urls got stacked together:
https://apod.nasa.gov/apod/http://nusoft.fnal.gov/nova/public/img/FD-evt-echo.gif
= 
https://apod.nasa.gov/apod/
&
http://nusoft.fnal.gov/nova/public/img/FD-evt-echo.gif

I suspect the second part is usually automatically appended to the first and works fine if the second part if a file location on the first and not a second URL.

If anyone wants to submit a pull request for code that checks for this scenario and corrects it, we'll consider approving the pull request.
