### ISSUE TITLE
API Key as a request header?

### ISSUE THREAD

**Issue by quiktea** [nasa/apod-api#61]
Currently we're forced to set our api keys in the `api_key` URL parameter. It would be extremely useful if we could set it in an `Authorization` header of some sort. It is also recommended to do it like this.

**Comment by elementh** [comment]
The APOD API, as well as all the other services that NASA provides ([here](https://api.nasa.gov/)) operate under the same auth system, some of the APIs are hosted by them and some of them are just proxies (see [NeoWS](https://api.nasa.gov/#asteroids-neows) for example). 
While your proposition has value, I think that you probably need to suggest this in other places instead:
- With an email to the official mail of the api.nasa.gov services: [`nasa-data@lists.arc.nasa.gov`](mailto:nasa-data@lists.arc.nasa.gov`)
- Opening an Issue on the api-docs girhub repo [here](https://github.com/nasa/api-docs)
- Contacting either [Jenna Horn](https://github.com/jmhorn2015) (the site developer) or [Brian Thomas](mailto:Brian.a.Thomas@nasa.gov) (the NASA official which I presume is in charge of api.nasa.gov)}

Good luck!

**Comment by quiktea** [comment]
I see, thank you very much

**Comment by mattiapontonio** [comment]
For the record
https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#the_general_http_authentication_framework
