### ISSUE TITLE
installing package through "python setup.py install" throws error of a missing directory "bin"

### ISSUE THREAD

**Issue by coder006** [nasa/apod-api#7]
```python
~/Documents/workspace/apod-api$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 39, in <module>
    scripts = [os.path.join("bin", file) for file in os.listdir("bin")]
FileNotFoundError: [Errno 2] No such file or directory: 'bin'
```
This is because the setup.py file is trying to list every file in the **bin** directory which does not exist:
https://github.com/nasa/apod-api/blob/master/setup.py#L39

**Comment by coder006** [comment]
Sorry, just saw that it only works on google app engine.
Is there any specific reason why this targets a specific platform?

**Comment by JustinGOSSES** [comment]
Couldn't replicate this problem in 2020 on MacOS or Linux. Please ping to re-open if it occurs again.
