### ISSUE TITLE
2018-10-07 date is not working.

### ISSUE THREAD

**Issue by hemangshah** [nasa/apod-api#8]
https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY&date=2018-10-07

Getting below error:
> {"code":500,"msg":"Internal Service Error","service_version":"v1"}

because of this, I can't even use the API request with start_date and end_date contains above date.

For example this API calls will also not work:

https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY&start_date=2018-10-07&end_date=2018-10-08

https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY&start_date=2018-10-01&end_date=2018-10-08

Please fix 7th October.  Looking forward to hearing back from you.

**Comment by samyanez94** [comment]
+1

I'm experiencing the same issue.

**Comment by PawelPleskaczynski** [comment]
If anyone needs a list of APODs (eg. from today to 20 days ago), I made a little API that doesn't throw 500 error when it contains 07.10.2018 APOD. If anyone is interested, here's the link: https://apod-wrapper.herokuapp.com/help

**Comment by samyanez94** [comment]
This work as a temporary solution. You are the MVP. Thanks @PawelPleskaczynski

**Comment by PawelPleskaczynski** [comment]
Thanks @samyanez94 :)
I will use it for my APOD client as well until NASA (hopefully) solves the problem.

**Comment by hemangshah** [comment]
@PawelPleskaczynski , how many requests one can make on that helper?

**Comment by PawelPleskaczynski** [comment]
Well, I haven't tried it yet, but according to [this website](https://devcenter.heroku.com/articles/limits), I'm limited to 4500 requests/h

**Comment by hemangshah** [comment]
@PawelPleskaczynski, awesome! Now we'll have to wait until Nasa Devs will approve your PR.

**Comment by hemangshah** [comment]
> Well, I haven't tried it yet, but according to [this website](https://devcenter.heroku.com/articles/limits), I'm limited to 4500 requests/h

Awesome! Heroku wins but NASA APOD API only allows 1000/h ;-)

**Comment by PawelPleskaczynski** [comment]
Yeah, let's hope they'll approve it! It's my first PR ever in my life so I'm pretty excited 😅

**Comment by eringrand** [comment]
Hello - is there an update on this issue?

**Comment by JustinGOSSES** [comment]
This problem has now been fixed.
