### ISSUE TITLE
Explanation parragraph is missing first letter - 2021-12-07

### ISSUE THREAD

**Issue by Eadwulf** [nasa/apod-api#87]
In the data retrived through the API, the explanation parragraph reads as:

`very time two massive black holes collide [...]`

while on the [APOD](https://apod.nasa.gov/apod/astropix.html) website, it reads as:

`Every time two massive black holes collide [...]`

Check the retrived data [here](https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY&date=2021-12-07).

**Comment by pinbraerts** [comment]
#119 Duplicate
