### ISSUE TITLE
Can you provide Thumbnails for video?

### ISSUE THREAD

**Issue by hemangshah** [nasa/apod-api#9]
There can be huge number of developers using APOD api for displaying every day APODs in a way that they want to. However, except image, when there'll be a video APOD, it's not easy to showcase a preview of the thumbnail.

In my current research- I have found that there can be videos from the following sources: YouTube, Vimeo and other. However, I have never came across the last type i.e. Other.

For YouTube it's little easy to create a thumbnail out of the video URL. But for Vimeo it's not easy at all. Vimeo requires you to make another API call to their server and from there you will get a thumbnail. 

Can we do this on APOD server and provide a thumbnail in the same `url` and `hdurl` parameters?

If you will provide this it will be much much easy for we developers.

**Comment by samyanez94** [comment]
+1

**Comment by JustinGOSSES** [comment]
fixed apparently via merge request
