### ISSUE TITLE
504 Gateway timeout on API fetch

### ISSUE THREAD

**Issue by Vroomfrondal** [nasa/apod-api#90]
Today I realized mine and multiple other APOD-api dependent web-applications aren't working. For mine, it's 504 Gateway timeouts on the fetch.

The documentation didn't seem to change, nor any announcements. Does anyone know if there is an issue or if its an endpoint change?

**Comment by Vroomfrondal** [comment]
Must've been a NASA server side issue. It's working fine now.

**Comment by Vroomfrondal** [comment]
More down time today. With fetch issues such as "Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)"

Not sure if its NASA's server or some kind of change

**Comment by AndrewCS149** [comment]
ALso having similar issues.

**Comment by Courtskit** [comment]
I am also having issues with this.  ""code":500,"msg":"Internal Service Error""

**Comment by tjosepo** [comment]
Same. I've been having issues for a few days. Some requests go through, but others fail with a basic 500 error. It's very inconsistent.

**Comment by lscheinhorn** [comment]
I'm having the same issue. It has been happening randomly for a week. I get a 500 error 'internal service error'
If I request specific dates it will return a result sometimes but today when I have a higher count value it returns a 500 error every time.

**Comment by Taylor-2T9** [comment]
The same thing happens to me. All my requests today are returning the same error (500 'Internal Service Error').

**Comment by Benanna2019** [comment]
I am also having this issue. The fetch from my api doesn't work at all. If I click on the link on api.nasa.gov to the Astrology Pic of the Day I get a gateway issue and then it refreshes and loads the singular image. 

If I type the url directly, with apikey and everything, it also gives the Status Code: 500, Internal Service Error. 

This is a job application for a large company that has this as part of their coding challenge before applying soooooo.....

**Comment by Semyon-Ivakaev** [comment]
Hello. I will also inform you that there are problems in the operation of the service. A very cool thing that I personally use. I hope for a speedy troubleshooting.
Спасибо!

**Comment by Vroomfrondal** [comment]
it appears to be working as of this post. going to leave the issue open until i’m sure it stops happening - as it’s been quite inconsistent

**Comment by lscheinhorn** [comment]
It's working now, so I put default count back to 12. I'm ready to set count back to 1 if it stops working so there would be a better chance of a successful fetch.

**Comment by lscheinhorn** [comment]
Works every time right now. So now it seems to be all or nothing. I'd love to know why it stops working for long periods of time. Traffic?

**Comment by tjosepo** [comment]
In case anyone in the future needs faces this problem, I re-wrote this API in JavaScript and you can deploy it to Deno Deploy for free. Deno Deploy is embarrassingly easy to use. You can have your own API in 3 click.

https://github.com/tjosepo/deno_apod
